Fix OS detection script in Makefile to ensure only Linux machines build TM binaries with cleveldb support

diff --git a/remote/networks/001-reference/Makefile b/remote/networks/001-reference/Makefile
--- a/remote/networks/001-reference/Makefile
+++ b/remote/networks/001-reference/Makefile
@@ -18,13 +18,14 @@ deploy:
 	@if [ "${FAST_MODE}" == "false" ]; then \
 		if [ "${WITH_CLEVELDB}" == "true" ]; then \
 			if [ "${UNAME_S}" != "Linux" ]; then \
-				$(error The cleveldb support can only be built from a Linux machine);
+				echo "ERROR: The cleveldb support can only be built from a Linux machine (yours is \"${UNAME_S}\")"; \
+				exit 1; \
 			fi; \
 			echo "Building Tendermint with cleveldb support..."; \
 			if [ "${INSTALL_TENDERMINT_LOCALLY}" == "true" ]; then \
 				CGO_LDFLAGS="-lsnappy" make -C $(TENDERMINT_SRC) install_c; \
 			fi; \
-			GOOS=linux GOARCH=amd64 CGO_LDFLAGS="-lsnappy" make -C $(TENDERMINT_SRC) build_c; \
+			CGO_LDFLAGS="-lsnappy" make -C $(TENDERMINT_SRC) build_c; \
 		else \
 			echo "Building Tendermint..."; \
 			if [ "${INSTALL_TENDERMINT_LOCALLY}" == "true" ]; then \
@@ -32,6 +33,7 @@ deploy:
 			fi; \
 			make -C $(TENDERMINT_SRC) build-linux; \
 		fi; \
+		echo "Building load testing tools..."; \
 		make -C $(TM_NETWORKS_SRC) tools-linux; \
 	fi
 	@rm -rf /tmp/nodes/
